spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    name: simple-resume
  port: 5000

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes